### ISSUE TITLE
Generated recipes for mods compat spam logs

### ISSUE THREAD

**Issue by Le6barbare** [CodersDownUnder/flowerseeds2#6]
Hello !

I'm using Flowerseeds2 in my modpack and have a large block of "[Render thread/INFO]: Skipping loading recipe flowerseeds:compat/\*\*\* as it's serializer returned null" lines in my logs

I'm using FlowerSeeds2-1.20.1-1.0.1 and Forge 47.1.47 and have reproduce this in test environment with only FlowerSeeds2 and JEI (v15.2.0.27) installed

After investigation, I found out it's because of the way the compat recipes are written/generated. Other mods with mod compatibility don't have this problem
for example, I don't have the corresponding INFO line in my log if I change the ["flowerseeds:compat/immersiveengineering/cloche/allium_seed" recipe](https://github.com/CodersDownUnder/flowerseeds2/blob/739049884981fdaaa3c5fb9da6fe670917037051/src/datagen/generated/flowerseeds/data/flowerseeds/recipes/compat/immersiveengineering/cloche/allium_seed.json) like this:

```JSON
{
  "conditions": [
    {
      "type": "forge:mod_loaded",
      "modid": "immersiveengineering"
      }
    ],
    "type": "immersiveengineering:cloche",
    "results": [
      {
        "item": "minecraft:allium"
      },
      {
        "item": "flowerseeds:allium_seed"
      }
    ],
    "input": {
      "item": "flowerseeds:allium_seed"
    },
    "soil": {
      "item": "minecraft:dirt"
    },
    "time": 240,
    "render": {
      "type": "crop",
      "block": "flowerseeds:allium_seed"
    }
}
```

I know it don't follow actual [Forge Documentation](https://docs.minecraftforge.net/en/1.20.x/resources/server/conditional/) but it works better that way and it is how other mods like Farmer's Delight do it

I hope you'll agree with me and change this, so we could have cleaner logs thus making debug easier :)

**Comment by Trhod17** [comment]
Should be fixed in v1.1.0

https://www.curseforge.com/minecraft/mc-mods/flower-seeds/files/4778550
